#!/usr/bin/env python3
"""Build index.html from the inlined font and the embedded template.

Run from anywhere; output goes to the repo root as index.html.
Requires Python 3.7+ and a base64-encoded font at src/fonts/noto.b64
(generated by build.sh from src/fonts/noto-sans-merged.ttf).
"""
from pathlib import Path

HERE = Path(__file__).resolve().parent
ROOT = HERE.parent
FONT_B64 = (HERE / "fonts" / "noto.b64").read_text().strip()
SRI_HASH = "JcnsjUPPylna1s1fvi1u12X5qjY5OL56iySh75FdtrwhO/SWXgMjoVqcKyIIWOLk"
OUT = ROOT / "index.html"

# Read the template from the existing index.html if present (allows quick
# tweaks by editing index.html directly), otherwise from template.html.
# This script only updates the font base64 and SRI hash placeholders; the
# rest of the HTML is preserved.
SOURCE = HERE / "template.html"
if not SOURCE.exists():
    raise SystemExit(
        f"Missing {SOURCE}. The template should live at src/template.html. "
        "If you previously edited index.html directly, copy it to src/template.html "
        "and replace the inlined font with the placeholder __FONT_BASE64__."
    )

template = SOURCE.read_text()
html = template.replace("__FONT_BASE64__", FONT_B64).replace("__SRI_HASH__", SRI_HASH)
OUT.write_text(html)
print(f"Wrote {OUT} ({len(html):,} bytes)")
